### ISSUE TITLE
Request to create a Web servers language family meta-buildpack

### ISSUE THREAD

**Issue by arjun024** [paketo-community/web-servers#1]
## Background

According to the [RFC 0006](https://github.com/paketo-buildpacks/rfcs/blob/main/text/0006-web-servers.md), a new language-family buildpack will be created that packages together the [NGINX Server](https://github.com/paketo-buildpacks/nginx), [Apache HTTP Server](https://github.com/paketo-buildpacks/httpd) and [Staticfile](https://github.com/paketo-community/staticfile) buildpacks together.

## Proposal

* Buildpack should have the id `paketo-community/web-servers` and name `Paketo Web Servers Buildpack`
* Follow the order grouping listed [here](https://github.com/paketo-buildpacks/rfcs/blob/main/accepted/0006-web-servers.md#implementation).
* Write integration tests using the [packit](https://github.com/paketo-buildpacks/packit), [occam](https://github.com/paketo-buildpacks/occam) libraries.
* Documentation in README
* Have github workflow automation setup per common [language-family github config](https://github.com/paketo-buildpacks/github-config/tree/main/language-family/.github)

**Comment by sophiewigmore** [comment]
To Do
- [ ] Buildpack should have the id `paketo-community/web-servers` and name `Paketo Web Servers Buildpack`
- [ ] Follow the order grouping listed [here](https://github.com/paketo-buildpacks/rfcs/blob/main/accepted/0006-web-servers.md#implementation).
- [ ] Write integration tests using the [packit](https://github.com/paketo-buildpacks/packit), [occam](https://github.com/paketo-buildpacks/occam) libraries.
- [ ] Documentation in README
- [ ] Have github workflow automation setup per common [language-family github config](https://github.com/paketo-buildpacks/github-config/tree/main/language-family/.github)

**Comment by ryanmoran** [comment]
@sophiewigmore can we not implement the `staticfile` portion of the RFC? I am having second thoughts on it and I'd like to see if we can drop support for that specific implementation.

**Comment by sophiewigmore** [comment]
@ryanmoran sure thing, I'll hold off. Ping me if you'd like to chat about this

**Comment by sophiewigmore** [comment]
Closed out by https://github.com/paketo-community/web-servers/pull/8
